# Generated by Django 6.0.7 on 2026-07-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=6, unique=True)),
                ('host_name', models.CharField(max_length=50)),
                ('guest_name', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('playing', 'Playing'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('current_turn', models.CharField(default='host', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
