# Generated by Django 6.0.7 on 2026-07-18 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('playing', 'Playing'), ('finished', 'Finished')], default='playing', max_length=20)),
                ('phase', models.CharField(choices=[('category_selection', 'Category Selection'), ('word_submission', 'Word Submission'), ('guessing', 'Guessing'), ('round_over', 'Round Over'), ('game_over', 'Game Over')], default='category_selection', max_length=30)),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('host_role', models.CharField(choices=[('guesser', 'Guesser'), ('setter', 'Setter')], default='guesser', max_length=20)),
                ('guest_role', models.CharField(choices=[('guesser', 'Guesser'), ('setter', 'Setter')], default='setter', max_length=20)),
                ('host_score', models.PositiveIntegerField(default=0)),
                ('guest_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='rooms.room')),
            ],
        ),
    ]
