# Generated by Django 6.0.7 on 2026-07-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='secret_word',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
