# Generated by Django 6.0.7 on 2026-07-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_game_category_alter_game_secret_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='correct_letters',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='remaining_lives',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='game',
            name='revealed_word',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='wrong_letters',
            field=models.JSONField(default=list),
        ),
    ]
