# Generated by Django 6.0.7 on 2026-07-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_game_correct_letters_game_remaining_lives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='hint_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='hint_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='hint_3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='hint_count',
            field=models.IntegerField(default=0),
        ),
    ]
