# Generated by Django 6.0.7 on 2026-07-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_game_hint_1_game_hint_2_game_hint_3_game_hint_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='match_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='match_winner',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='winning_score',
            field=models.IntegerField(default=5),
        ),
    ]
